# -*- coding: utf-8 -*-
"""Session 2_Alvi Aulia F_2602182865.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMsDXeJjSlpkZQqPsJgO-HBt2FenblB5

Seq 1 = 'ATGCATGGTGCGCGA’​

Seq 2 = 'ATTTGTGCTCCTGGA’​

# Seq yang memiliki GC tertinggi
"""

#Installation (try !pip for native anaconda distribution or pip for google colab)
!pip install biopython

# Load Bioinformatic Pkgs
import Bio

from Bio.Seq import Seq

Dna_Seq = Seq('ATGCATGGTGCGCGA')

from Bio.SeqUtils import GC123

Dna_Seq

GC123(Dna_Seq)

# Method 2
# Custom Fxn to Get GC Count
Dna_Seq.count('A')

def gc_content(seq):
    result = float(seq.count('G') + seq.count('C'))/len(seq) * 100
    return result

gc_content(Dna_Seq)

# Method 3
def gc_content2(seq):
    gc = [ B for B in seq.upper() if B in 'GC']
    result = float(len(gc))/len(seq) * 100
    return result

gc_content2(Dna_Seq)

Dna_Seq.lower()

gc_content2('ATTTGTGCTCCTGGA')

GC123('ATTTGTGCTCCTGGA')

# Fxn for AT content
def at_content(seq):
    result = float(seq.count('A') + seq.count('T'))/len(seq) * 100
    return result

at_content(Dna_Seq)

"""JAWABAN SOAL NO 1:\
Hasil GC:\
Seq 1 = 'ATGCATGGTGCGCGA’​ : 60.0\
Seq 2 = 'ATTTGTGCTCCTGGA’​ : 46.666666666666664

Jadi Sequence 1 memiliki nilai GC yang lebih tinggi

# Seq yang mempunyai suhu leleh lebih tinggi
"""

import Bio.SeqUtils

dir(Bio.SeqUtils)

from Bio.SeqUtils import MeltingTemp as mt

Dna_Seq

GC123(Dna_Seq)

# check for the melting point using wallace
mt.Tm_Wallace(Dna_Seq)

# Check for the melting point using GC content
mt.Tm_GC(Dna_Seq)

Sequence1 = Seq('ATGCATGGTGCGCGA')
Sequence2 = Seq('ATTTGTGCTCCTGGA')

#Menggunakan GC
def get_metrics(seq):
    gc = GC123(seq)
    at = at_content(seq)
    melting = mt.Tm_GC(seq)
    result = "GC:{} ,AT:{}, Temp:{}".format(gc,at,melting)
    return result

get_metrics(Sequence1)

get_metrics(Sequence2)

#Menggunakan Wallace
def get_metrics(seq):
    melting = mt.Tm_Wallace(seq)
    result = "Temp:{}".format(melting)
    return result

"""JAWABAN SOAL NO 2:\
Hasil Suhu Leleh:\
Seq 1 = 'ATGCATGGTGCGCGA’​ : 44.5029020719779\
Seq 2 = 'ATTTGTGCTCCTGGA’​ : 39.03623540531123

Jadi Sequence 1 memiliki nilai suhu leleh yang lebih tinggi

# Seq yang memiliki berat molekul tertinggi
"""

!pip install biopython

from Bio.Seq import Seq
from Bio.SeqUtils import molecular_weight

Dna1 = Seq('ATGCATGGTGCGCGA')
Dna2 = Seq('ATTTGTGCTCCTGGA')

weight = molecular_weight (Dna1)
print(weight)

weight = molecular_weight (Dna2)
print(weight)

"""JAWABAN SOAL NO 3:\
Hasil Berat Molekul:\
Seq 1 = 'ATGCATGGTGCGCGA’​ : 4712.995199999999\
Seq 2 = 'ATTTGTGCTCCTGGA’​ : 4653.9565

Jadi Sequence 1 memiliki berat molekul yang lebih tinggi
"""