# -*- coding: utf-8 -*-
"""Session 1_Alvi Aulia F_2602182865.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJ32_4goWlfKSLldJJJYMUzxurQa5Imb

Nama : Alvi Aulia Fatikha
NIM : 2602182865

Biopython Installation
"""

#Installation (try !pip for native anaconda distribution or pip for google colab)
!pip install biopython

# Load Bioinformatic Pkgs
import Bio

# Methods and Attributes
dir(Bio)

"""Sequences"""

from Bio.Seq import Seq

# Methods of Seq
dir(Seq);

# Create A simple sequences
seq1 = Seq('ATGCATGGTGCGCGA')
seq1

"""Sequence Manipulation"""

# Length of our seq
len(seq1)

len('ATGCATGGTGCGCGA')

# Slicing
seq1[0:3]

# Reverse
seq1[::-1]

seq2 = Seq('ATTTGTGCTCCTGGA')

# Join Seq
seq1[0:6] + seq2

# Find the number of Nucleotides/Base within our seq
# Count
seq1.count('G')

seq1.count('A')

# Count the number of codon (3B) within a seq
seq1.count('ATG')

# Find the position/location of a nucleotide
seq1.find('G')

seq1

# Find the position/location of a nucleotide from the right
seq1.rfind('G')

# Find the location/index using index
seq1.index('G')

# Find the location/index using index
seq1.rindex('G')



"""Subsequences"""

from Bio.SeqUtils import nt_search

main_seq = Seq('ACTATT')
subseq = Seq('ATT')

nt_search(str(main_seq),str(subseq))

"""Plot of Frequency of Nucleotides/Base"""

pip install matplotlib

import matplotlib.pyplot as plt

from collections import Counter

dna_seq = Seq('ATGCATGGTGCGCGA')

dna_freq = Counter(dna_seq)
dna_freq

plt.bar(dna_freq.keys(),dna_freq.values())