# -*- coding: utf-8 -*-
"""AlviAuliaFatikha_BE20_2602182865_Session3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMnXWMG8czrB0-SMGF0IZBM9xWp3n9Ze

#Protein Synthesis
"""

#Installation (try !pip for native anaconda distribution or pip for google colab)
!pip install biopython

# Load Bioinformatic Pkgs
import Bio

from Bio.Seq import Seq

dna_seq = Seq('ATGATCTCGTAA')

len(dna_seq)

dna_seq.complement()

dna_seq.reverse_complement()

dna_seq.complement()[::-1]

dna_seq

dna_seq.transcribe()

mRNA = dna_seq.transcribe()

mRNA.translate()

dna_seq.translate()

mRNA.translate(stop_symbol="@")

mRNA.back_transcribe()

mRNA.back_transcribe() == dna_seq

dna_seq.transcribe().translate()

from Bio.SeqUtils import seq3,seq1

aa = dna_seq.translate()
aa

seq3(aa)

seq1('MetIleSerTer')

"""#Amino Acids"""

from Bio.Data import CodonTable

dir(CodonTable)

print(CodonTable.unambiguous_dna_by_name['Standard'])

print(CodonTable.unambiguous_rna_by_name['Standard'])

"""#3D Structure of Protein"""

import os
from Bio.PDB.PDBParser import PDBParser

parser = PDBParser()
pdb_file = os.path.abspath("/content/6lu7.pdb")

structure = parser.get_structure("6LU7", pdb_file)

structure

model = structure[0]

for chain in model:
  print(f'Chain {chain}, Chain_ID{chain.id}')

for chain in model:
  print(f'Chain {chain}, Chain_ID{chain.id}')
  for residue in chain:
    print(residue)

for chain in model:
  print(f'Chain {chain}, Chain_ID{chain.id}')
  for residue in chain:
    for atom in residue:
      print(atom)

!pip install py3Dmol
import py3Dmol

view1 = py3Dmol.view(query='pdb:6LU7')
view1.setStyle({'cartoon':{'color':'spectrum'}})